version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "mysql"
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "user"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/conf.d/my.conf:/etc/mysql/conf.d/my.conf"

